### ISSUE TITLE
Objective-C? Swift?

### ISSUE THREAD

**Issue by nikolakulikov** [ReDetection/audioreview#1]
Здравствуйте, Сергей!
Сразу хочу извиниться, что пишу вам в гитхаб.
Я ищу разработчика с опытом в Objective-C (который у вас есть, судя по репозиторию :), хотя бы пониманием Swift, возможностью разговаривать хотя бы на ломаном английском и суммарным опытом в iOS от 2 до 100 лет :)
Напишите, пожалуйста, в скайп cv.kulikov@gmail.com (это именно скайп), если это про вас :)
Спасибо

**Comment by ReDetection** [comment]
Feel free to mail me, but please do not use Issues for this.
